services:
  backend:
    build: ./backend/server
    ports:
      - "8080:8080"
    networks:
      - uknight-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - uknight-network
    depends_on:
      - backend

networks:
  uknight-network:
    driver: bridge
